# Site settings
title: Bad Android!
email: nocontact@nomail.com
description: >
    Android Malware Analysis Blog
paginate: 10
highlighter: pygments
name: Solar Theme
permalink: /
baseurl: ""
url: "http://badandroid.github.io"
twitter_username: abpolym
github_username:  badandroid

# Build settings
markdown: kramdown
